### ISSUE TITLE
FYI: Name conflict with devops tool

### ISSUE THREAD

**Issue by DDuTCH** [sintaxi/terraform#134]
Was searching for something related to Hashicorp's Terraform on NPM. Found this instead.
https://www.terraform.io

May want to at least add a statement that you're not affiliated with them or something?

**Comment by sintaxi** [comment]
It's stated clearly at the top of the repo as well as published packages what this lib is for.

> Terraform is the pre-processor engine for the Harp web server. Terraform does not write or serve files. It processes and provides a layout/partial paradigm.

https://github.com/sintaxi/terraform/blob/master/README.md
https://www.npmjs.com/package/terraform
