### ISSUE TITLE
If you ever desire an alternative to marked...

### ISSUE THREAD

**Issue by howardroark** [sintaxi/terraform#62]
This is a bit of a troll issue, so just yell at me if you want it closed.  I have been watching the marked project for some time and find that it does seem to lack leadership.

A bunch of Russian dudes who are obsessed with speed and efficiency have started to gut and rebuild it. They are being super diligent to ensure that it works really well. They also take cues from the "CommonMark" project when it does make sense. It is all under the leadership of the guy who runs assemble.io, he is a super awesome dude with infinite patience.

https://github.com/jonschlinkert/remarkable

...Something to think about :)  It is still a work in progress... but maybe you already have some thoughts that you would like to drop in the bucket.

**Comment by kennethormandy** [comment]
We ended up sticking with Marked and going with the generators feature. Appreciate you bringing this to our attention though. :)
