### ISSUE TITLE
Unable to install it on windows 8

### ISSUE THREAD

**Issue by mcbjam** [sintaxi/terraform#76]
Unable to install it with windows8. I have this error 

D:\github\blaguesexy>npm install -g terraform
npm http GET https://registry.npmjs.org/terraform
npm http 200 https://registry.npmjs.org/terraform
npm http GET https://registry.npmjs.org/lru-cache/2.5.0
npm http GET https://registry.npmjs.org/jade/0.35.0
npm http GET https://registry.npmjs.org/coffee-script/1.7.1
npm http GET https://registry.npmjs.org/ejs/1.0.0
npm http GET https://registry.npmjs.org/node-sass/0.9.3
npm http GET https://registry.npmjs.org/marked/0.2.9
npm http GET https://registry.npmjs.org/less/1.7.4
npm http GET https://registry.npmjs.org/stylus/0.47.3
npm http GET https://registry.npmjs.org/autoprefixer
npm http 304 https://registry.npmjs.org/coffee-script/1.7.1
npm http 304 https://registry.npmjs.org/node-sass/0.9.3
npm http 304 https://registry.npmjs.org/marked/0.2.9
npm http 304 https://registry.npmjs.org/jade/0.35.0
npm http 304 https://registry.npmjs.org/ejs/1.0.0
npm http 304 https://registry.npmjs.org/autoprefixer
npm http 304 https://registry.npmjs.org/lru-cache/2.5.0
npm http 304 https://registry.npmjs.org/stylus/0.47.3
npm http 304 https://registry.npmjs.org/less/1.7.4
npm http GET https://registry.npmjs.org/caniuse-db
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/postcss
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/caniuse-db
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/postcss
npm http 304 https://registry.npmjs.org/mkdirp
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'C:\Users\mouni_000\AppData\
Roaming\npm\node_modules\terraform\node_modules\less\dist'
npm ERR! error rolling back  terraform@0.9.0 { [Error: ENOTEMPTY, rmdir 'C:\User
s\mouni_000\AppData\Roaming\npm\node_modules\terraform\node_modules\less\dist']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'C:\\Users\\mouni_000\\AppData\\Roaming\\npm
\\node_modules\\terraform\\node_modules\\less\\dist' }
npm ERR! Error: No compatible version found: caniuse-db@'^1.0.20140727'
npm ERR! Valid install targets:
npm ERR! ["1.0.20140224","1.0.20140225","1.0.20140226","1.0.20140301","1.0.20140
302","1.0.20140303","1.0.20140304","1.0.20140306","1.0.20140311","1.0.20140313",
"1.0.20140316","1.0.20140318","1.0.20140319","1.0.20140325","1.0.20140326","1.0.
20140330","1.0.20140331","1.0.20140401","1.0.20140403","1.0.20140409","1.0.20140
412","1.0.20140416","1.0.20140422","1.0.20140428","1.0.20140429","1.0.20140502",
"1.0.20140504","1.0.20140505","1.0.20140506","1.0.20140507","1.0.20140511","1.0.
20140516","1.0.20140519","1.0.20140520","1.0.20140521","1.0.20140523","1.0.20140
526","1.0.20140529","1.0.20140601","1.0.20140602","1.0.20140603","1.0.20140606",
"1.0.20140608","1.0.20140609","1.0.20140610","1.0.20140611","1.0.20140616","1.0.
20140617","1.0.20140618","1.0.20140619","1.0.20140622","1.0.20140623","1.0.20140
626","1.0.20140628","1.0.20140702","1.0.20140710","1.0.20140715","1.0.20140716",
"1.0.20140717","1.0.20140721","1.0.20140722","1.0.20140724","1.0.20140726","1.0.
20140727","1.0.20140728","1.0.20140729","1.0.20140730","1.0.20140731","1.0.20140
801","1.0.20140804","1.0.20140810","1.0.20140811","1.0.20140812","1.0.20140814",
"1.0.20140815","1.0.20140816","1.0.20140820","1.0.20140821","1.0.20140826","1.0.
20140827","1.0.20140902","1.0.20140903","1.0.20140906","1.0.20140908","1.0.20140
909","1.0.20140910","1.0.20140911","1.0.20140915","1.0.20140916","1.0.20140918",
"1.0.20140922","1.0.20140924","1.0.20140928","1.0.20140929","1.0.20141001","1.0.
20141006","1.0.20141007","1.0.20141008","1.0.30000001","1.0.30000002","1.0.30000
003","1.0.30000004","1.0.30000005","1.0.30000006","1.0.30000007","1.0.30000008",
"1.0.30000009","1.0.30000010","1.0.30000011","1.0.30000012","1.0.30000013","1.0.
30000014","1.0.30000015","1.0.30000016","1.0.30000017","1.0.30000018","1.0.30000
019","1.0.30000020","1.0.30000021","1.0.30000022","1.0.30000023","1.0.30000024",
"1.0.30000025","1.0.30000026","1.0.30000027","1.0.30000028","1.0.30000029","1.0.
30000030","1.0.30000031","1.0.30000032","1.0.30000033","1.0.30000034","1.0.30000
035","1.0.30000036","1.0.30000037","1.0.30000038","1.0.30000039","1.0.30000040",
"1.0.30000041","1.0.30000042","1.0.30000043","1.0.30000044","1.0.30000045","1.0.
30000046","1.0.30000047","1.0.30000048","1.0.30000049","1.0.30000050","1.0.30000
051","1.0.30000052","1.0.30000053","1.0.30000054","1.0.30000055","1.0.30000056",
"1.0.30000057","1.0.30000058","1.0.30000059"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:685:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:607:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm
-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "terraform"
npm ERR! cwd D:\github\blaguesexy
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! Error: ENOENT, lstat 'C:\Users\mouni_000\AppData\Roaming\npm\node_modul
es\terraform\node_modules\coffee-script\node_modules\mkdirp\package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "terraform"
npm ERR! cwd D:\github\blaguesexy
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraform\node
_modules\coffee-script\node_modules\mkdirp\package.json
npm ERR! fstream_path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraf
orm\node_modules\coffee-script\node_modules\mkdirp\package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\mouni_000\AppData\Roaming\npm\node_modul
es\terraform\node_modules\jade\lib\nodes\literal.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "terraform"
npm ERR! cwd D:\github\blaguesexy
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraform\node
_modules\jade\lib\nodes\literal.js
npm ERR! fstream_path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraf
orm\node_modules\jade\lib\nodes\literal.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\mouni_000\AppData\Roaming\npm\node_modul
es\terraform\node_modules\less\dist\less-1.6.0.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "terraform"
npm ERR! cwd D:\github\blaguesexy
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraform\node
_modules\less\dist\less-1.6.0.js
npm ERR! fstream_path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraf
orm\node_modules\less\dist\less-1.6.0.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\mouni_000\AppData\Roaming\npm\node_modul
es\terraform\node_modules\node-sass\libsass\prelexer.cpp'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "terraform"
npm ERR! cwd D:\github\blaguesexy
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraform\node
_modules\node-sass\libsass\prelexer.cpp
npm ERR! fstream_path C:\Users\mouni_000\AppData\Roaming\npm\node_modules\terraf
orm\node_modules\node-sass\libsass\prelexer.cpp
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\github\blaguesexy\npm-debug.log
npm ERR! not ok code 0

I already tried to clean the repository but no way.

It was the same when i tried to install harp.

**Comment by kennethormandy** [comment]
Thanks for opening an issue. Harp and Terraform should both work on Windows 8, I don’t see an immediate reason for that. Would you mind trying to run the tests for us?

```
git clone https://github.com/sintaxi/terraform
cd terraform
npm install
npm test
```

And posting any results from that? Thanks!

**Comment by mcbjam** [comment]
Hi.

Here is the error i got : 

    npm http 304 https://registry.npmjs.org/uglify-js/2.4.0
npm http 304 https://registry.npmjs.org/css
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/caniuse-db
npm ERR! Error: No compatible version found: caniuse-db@'^1.0.20140727'
npm ERR! Valid install targets:
npm ERR! ["1.0.20140224","1.0.20140225","1.0.20140226","1.0.20140301","1.0.20140
302","1.0.20140303","1.0.20140304","1.0.20140306","1.0.20140311","1.0.20140313",
"1.0.20140316","1.0.20140318","1.0.20140319","1.0.20140325","1.0.20140326","1.0.
20140330","1.0.20140331","1.0.20140401","1.0.20140403","1.0.20140409","1.0.20140
412","1.0.20140416","1.0.20140422","1.0.20140428","1.0.20140429","1.0.20140502",
"1.0.20140504","1.0.20140505","1.0.20140506","1.0.20140507","1.0.20140511","1.0.
20140516","1.0.20140519","1.0.20140520","1.0.20140521","1.0.20140523","1.0.20140
526","1.0.20140529","1.0.20140601","1.0.20140602","1.0.20140603","1.0.20140606",
"1.0.20140608","1.0.20140609","1.0.20140610","1.0.20140611","1.0.20140616","1.0.
20140617","1.0.20140618","1.0.20140619","1.0.20140622","1.0.20140623","1.0.20140
626","1.0.20140628","1.0.20140702","1.0.20140710","1.0.20140715","1.0.20140716",
"1.0.20140717","1.0.20140721","1.0.20140722","1.0.20140724","1.0.20140726","1.0.
20140727","1.0.20140728","1.0.20140729","1.0.20140730","1.0.20140731","1.0.20140
801","1.0.20140804","1.0.20140810","1.0.20140811","1.0.20140812","1.0.20140814",
"1.0.20140815","1.0.20140816","1.0.20140820","1.0.20140821","1.0.20140826","1.0.
20140827","1.0.20140902","1.0.20140903","1.0.20140906","1.0.20140908","1.0.20140
909","1.0.20140910","1.0.20140911","1.0.20140915","1.0.20140916","1.0.20140918",
"1.0.20140922","1.0.20140924","1.0.20140928","1.0.20140929","1.0.20141001","1.0.
20141006","1.0.20141007","1.0.20141008","1.0.30000001","1.0.30000002","1.0.30000
003","1.0.30000004","1.0.30000005","1.0.30000006","1.0.30000007","1.0.30000008",
"1.0.30000009","1.0.30000010","1.0.30000011","1.0.30000012","1.0.30000013","1.0.
30000014","1.0.30000015","1.0.30000016","1.0.30000017","1.0.30000018","1.0.30000
019","1.0.30000020","1.0.30000021","1.0.30000022","1.0.30000023","1.0.30000024",
"1.0.30000025","1.0.30000026","1.0.30000027","1.0.30000028","1.0.30000029","1.0.
30000030","1.0.30000031","1.0.30000032","1.0.30000033","1.0.30000034","1.0.30000
035","1.0.30000036","1.0.30000037","1.0.30000038","1.0.30000039","1.0.30000040",
"1.0.30000041","1.0.30000042","1.0.30000043","1.0.30000044","1.0.30000045","1.0.
30000046","1.0.30000047","1.0.30000048","1.0.30000049","1.0.30000050","1.0.30000
051","1.0.30000052","1.0.30000053","1.0.30000054","1.0.30000055","1.0.30000056",
"1.0.30000057","1.0.30000058","1.0.30000059"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:685:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:607:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm
-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\github\blaguesexy\terraform
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm http 304 https://registry.npmjs.org/postcss
npm http GET https://registry.npmjs.org/is-promise
npm http GET https://registry.npmjs.org/css-parse/1.0.4
npm http GET https://registry.npmjs.org/css-stringify/1.0.5
npm http 304 https://registry.npmjs.org/css-parse/1.0.4
npm http 304 https://registry.npmjs.org/css-stringify/1.0.5
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/is-promise
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/source-map



NB : 1. I already use harp for several website
2. I had a local installation of harp with the version 0.12.1 and terraform 0.7.0. This version work on my computer, but i was not able to install it. I was not able ti do
        npm install -harp@0.12.1
3. Evrything else work fine

In advance thanks for your help.

**Comment by kennethormandy** [comment]
I’ll see if I can reproduce it, but I probably won’t be able to get to it until next week. It looks like it might have a problem when trying to install Autoprefixer.

Just so I know what to test with, you’re running Window 8, not Windows 8.1, correct?

**Comment by mcbjam** [comment]
Yes, i'm using windows 8 64 bit

I'm impatient to get yout corrections. Please don't forget me( my jo is blok).

In advance thanks for your help.

**Comment by kennethormandy** [comment]
If you need Harp v0.12.1 in the meantime, this should still work:

```
npm install --global harp@v0.12.1
```

If there’s a problem with that command, it might be indicative of a larger problem. If I haven’t answered by Tuesday, definitely post here again or [tweet to @HarpWebServer](http://twitter.com/harpwebserver).

**Comment by mcbjam** [comment]
Hi. I tried several version of harp and i have an error. I tried to install them locally or globally.

Like i tell you, something is weired -> I copied a harp module repository locally from another project and it work fine as a middelware in nodejs. So no problem for execute the module but there are a problem when i try to install it in a new project or globally.

Are there any way to manually install globally the package from an unzipp module folder coming from another project ? My purpose is to get the harp command to generate some static file.

In advance thanks.

**Comment by mcbjam** [comment]
Sorry for my English. And good weekend.

JAMIL Mounir


2015-01-29 23:01 GMT+01:00 Kenneth Ormandy <notifications@github.com>:

**Comment by mcbjam** [comment]
Hi, were you able to look like to this bug ?

**Comment by mcbjam** [comment]
The bug is gone after reinstallation if node.

**Comment by kennethormandy** [comment]
Thanks for keeping us updated! Glad it’s sorted. If any other Windows-specific comes up, definitely let me know.
