### ISSUE TITLE
Allow customization of processor

### ISSUE THREAD

**Issue by mckramer** [sintaxi/terraform#86]
I'd love the ability to customize the marked renderer in [/lib/template/processors/md.js](https://github.com/sintaxi/terraform/blob/master/lib/template/processors/md.js).

What do you think about an API that either allows providing options or a brand new renderer?  Or some way to replace an existing processor?

**Comment by kennethormandy** [comment]
Hey! Thanks for opening an issue. You might be able to use npm shrinkwrap to modify [Terraform’s](https://github.com/sintaxi/terraform) dependencies, or fork it, but otherwise we have no immediate plans to make this configurable.
