### ISSUE TITLE
Update node-sass dep to 3.0.0-beta

### ISSUE THREAD

**Issue by xzyfer** [sintaxi/terraform#88]
Terraform currently depends on an old 3.0.0-alpha release. We've since release 5 new betas with a 6th about to drop. These betas bring a lot to users including a new release of Libsass, and broader runtime and os support.

I believe there may be some minor API changes but it should be a trivial update.

/cc @djensen47

**Comment by kennethormandy** [comment]
Hey! Hope everything’s going well with you. Sorry if this caused any distractions on your issue tracker. 

The latest release of Terraform on npm is actually using 2.x still, and we’re just prepping to do another release with 3.x. We’ll definitely make sure to use the latest beta. /cc @sintaxi

**Comment by xzyfer** [comment]
Hey! I didn't realise this was your project, hope all is well.

The node-sass issues was regarding the 2.x series, which is latest stable. I noticed you were preparing for 3.0.0 and wanted to jump in before you shipped. Thanks for the quick response.

**Comment by djensen47** [comment]
Would it be possible to update to the node-sass dependency to "3.0.0-beta.7" or "3.0.0@beta"?

Thanks!
